"""'target_uuid' renamed to 'source_uuid', 'target_search' to 'seach_query'

Revision ID: 03dc45fafb9d
Revises: 910a42b39d3f
Create Date: 2019-07-25 12:39:24.100470

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '03dc45fafb9d'
down_revision = '910a42b39d3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_instances', sa.Column('source_uuid', postgresql.UUID(as_uuid=True), nullable=True))
    op.drop_constraint('task_instances_target_uuid_fkey', 'task_instances', type_='foreignkey')
    op.create_foreign_key(None, 'task_instances', 'task_instances', ['source_uuid'], ['uuid'])
    op.drop_column('task_instances', 'target_uuid')
    op.add_column('tasks', sa.Column('search_query', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.drop_constraint('uq_task_type_task_parameters', 'tasks', type_='unique')
    op.create_unique_constraint('uq_task_type_task_parameters', 'tasks', ['task_type', 'utility_name', 'search_query', 'utility_parameters'])
    op.drop_column('tasks', 'search')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('search', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_constraint('uq_task_type_task_parameters', 'tasks', type_='unique')
    op.create_unique_constraint('uq_task_type_task_parameters', 'tasks', ['task_type', 'utility_name', 'search', 'utility_parameters'])
    op.drop_column('tasks', 'search_query')
    op.add_column('task_instances', sa.Column('target_uuid', postgresql.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'task_instances', type_='foreignkey')
    op.create_foreign_key('task_instances_target_uuid_fkey', 'task_instances', 'task_instances', ['target_uuid'], ['uuid'])
    op.drop_column('task_instances', 'source_uuid')
    # ### end Alembic commands ###
