"""force refresh is boolean

Revision ID: 1529ea65cf33
Revises: f864f8f08022
Create Date: 2019-06-26 11:21:06.819124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1529ea65cf33'
down_revision = 'f864f8f08022'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('force_refresh', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'force_refresh')
    # ### end Alembic commands ###
