"""empty message

Revision ID: 15d2172622b3
Revises: 03dc45fafb9d
Create Date: 2019-07-29 10:38:16.752511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15d2172622b3'
down_revision = '03dc45fafb9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('results', sa.Column('interestingness', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('results', 'interestingness')
    # ### end Alembic commands ###
