"""empty message

Revision ID: 2610d9cb8c80
Revises: 379765a68592
Create Date: 2019-08-26 14:29:52.380597

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2610d9cb8c80'
down_revision = '379765a68592'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('result_id', sa.Integer(), nullable=True))
    op.drop_constraint('reports_task_id_fkey', 'reports', type_='foreignkey')
    op.create_foreign_key(None, 'reports', 'results', ['result_id'], ['id'])
    op.drop_column('reports', 'task_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('task_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'reports', type_='foreignkey')
    op.create_foreign_key('reports_task_id_fkey', 'reports', 'tasks', ['task_id'], ['id'])
    op.drop_column('reports', 'result_id')
    # ### end Alembic commands ###
