"""Add a unique constraint to Query

Revision ID: 28ece9519d21
Revises: 1fb43417d846
Create Date: 2019-03-08 13:48:06.523526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28ece9519d21'
down_revision = '1fb43417d846'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_queries_query_type_query_parameters', 'queries', ['query_type', 'query_parameters'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_queries_query_type_query_parameters', 'queries', type_='unique')
    # ### end Alembic commands ###
