"""force refresh is removed from task_parameters into a separate column

Revision ID: 3b8dc8150ff2
Revises: dcd1ce34e74f
Create Date: 2019-06-26 10:55:11.679928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b8dc8150ff2'
down_revision = 'dcd1ce34e74f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('force_refresh', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'force_refresh')
    # ### end Alembic commands ###
