"""Adjust tasks and reports to support multiple reports per task

Revision ID: 5c2129e04f20
Revises: 5c777ff8a423
Create Date: 2019-04-09 12:35:57.163759

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5c2129e04f20'
down_revision = '5c777ff8a423'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('report_format', sa.String(length=255), nullable=True))
    op.add_column('reports', sa.Column('report_language', sa.String(length=255), nullable=True))
    op.add_column('reports', sa.Column('task_uuid', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_foreign_key(None, 'reports', 'tasks', ['task_uuid'], ['uuid'])
    op.drop_constraint('tasks_report_id_fkey', 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'report_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('report_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('tasks_report_id_fkey', 'tasks', 'reports', ['report_id'], ['id'])
    op.drop_constraint(None, 'reports', type_='foreignkey')
    op.drop_column('reports', 'task_uuid')
    op.drop_column('reports', 'report_language')
    op.drop_column('reports', 'report_format')
    # ### end Alembic commands ###
