"""Rename column report to report_content

Revision ID: 5c777ff8a423
Revises: fe10822b1463
Create Date: 2019-04-09 11:53:59.101714

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5c777ff8a423'
down_revision = 'fe10822b1463'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reports', 'report', new_column_name='report_content')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reports', 'report_content', new_column_name='report')
    # ### end Alembic commands ###


# def upgrade():
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.add_column('reports', sa.Column('report_content', sa.JSON(), nullable=True))
#     op.drop_column('reports', 'report')
#     # ### end Alembic commands ###
#
#
# def downgrade():
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.add_column('reports', sa.Column('report', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
#     op.drop_column('reports', 'report_content')
#     # ### end Alembic commands ###
