"""target_uuid as a separate column

Revision ID: 95717ed8afff
Revises: 1529ea65cf33
Create Date: 2019-07-04 10:11:47.948987

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '95717ed8afff'
down_revision = '1529ea65cf33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('target_uuid', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_foreign_key(None, 'tasks', 'tasks', ['target_uuid'], ['uuid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'target_uuid')
    # ### end Alembic commands ###
