"""Fix task id links

Revision ID: b85cd1a48e6c
Revises: 28ece9519d21
Create Date: 2019-03-08 14:43:49.930974

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b85cd1a48e6c'
down_revision = '28ece9519d21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('data_parent_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.add_column('tasks', sa.Column('hist_parent_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.drop_constraint('tasks_data_source_id_fkey', 'tasks', type_='foreignkey')
    op.drop_constraint('tasks_prev_id_fkey', 'tasks', type_='foreignkey')
    op.create_foreign_key(None, 'tasks', 'tasks', ['hist_parent_id'], ['uuid'])
    op.create_foreign_key(None, 'tasks', 'tasks', ['data_parent_id'], ['uuid'])
    op.drop_column('tasks', 'prev_id')
    op.drop_column('tasks', 'data_source_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('data_source_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('tasks', sa.Column('prev_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.create_foreign_key('tasks_prev_id_fkey', 'tasks', 'tasks', ['prev_id'], ['id'])
    op.create_foreign_key('tasks_data_source_id_fkey', 'tasks', 'tasks', ['data_source_id'], ['id'])
    op.drop_column('tasks', 'hist_parent_id')
    op.drop_column('tasks', 'data_parent_id')
    # ### end Alembic commands ###
