"""Rename current_task to current_task_id

Revision ID: c9adeb1cd228
Revises: e86a9cb265e2
Create Date: 2019-03-07 14:56:45.064085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9adeb1cd228'
down_revision = 'e86a9cb265e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('current_task_id', sa.Integer(), nullable=True))
    op.drop_constraint('users_current_task_fkey', 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'tasks', ['current_task_id'], ['id'])
    op.drop_column('users', 'current_task')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('current_task', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key('users_current_task_fkey', 'users', 'tasks', ['current_task'], ['id'])
    op.drop_column('users', 'current_task_id')
    # ### end Alembic commands ###
