"""Remove obsolete column data_parent_id from tasks

Revision ID: dcd1ce34e74f
Revises: 5c2129e04f20
Create Date: 2019-04-16 17:03:48.851914

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'dcd1ce34e74f'
down_revision = '5c2129e04f20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('tasks_data_parent_id_fkey', 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'data_parent_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('data_parent_id', postgresql.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('tasks_data_parent_id_fkey', 'tasks', 'tasks', ['data_parent_id'], ['uuid'])
    # ### end Alembic commands ###
