"""Add current_task to users

Revision ID: e86a9cb265e2
Revises: bf9088bd1511
Create Date: 2019-03-07 13:37:10.280873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e86a9cb265e2'
down_revision = 'bf9088bd1511'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('current_task', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'tasks', ['current_task'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'current_task')
    # ### end Alembic commands ###
