"""Add new table for reports

Revision ID: fe10822b1463
Revises: 35654ff50445
Create Date: 2019-04-09 11:26:19.071421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe10822b1463'
down_revision = '35654ff50445'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report', sa.JSON(), nullable=True),
    sa.Column('report_generated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('tasks', sa.Column('report_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tasks', 'reports', ['report_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'report_id')
    op.drop_table('reports')
    # ### end Alembic commands ###
